# Generated by Django 5.0.1 on 2024-02-09 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('speciality', '0001_initial'),
        ('trusts', '0003_alter_region_id_alter_trust_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='jd_documents/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('primarySpecialities', models.ManyToManyField(related_name='primary_speciality', to='speciality.speciality')),
                ('subSpecialities', models.ManyToManyField(related_name='sub_speciality', to='speciality.speciality')),
                ('trust', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trusts.trust')),
            ],
        ),
    ]
