# Generated by Django 5.0.1 on 2024-02-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='jd_documents/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
