# Generated by Django 5.0.1 on 2024-02-07 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jd', '0001_initial'),
        ('trusts', '0003_alter_region_id_alter_trust_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jd',
            name='trust',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trusts.trust'),
        ),
    ]
