# Generated by Django 5.0.1 on 2024-02-09 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jd', '0001_initial'),
        ('speciality', '0004_alter_consultanttype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jd',
            name='consultantType',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='speciality.consultanttype'),
            preserve_default=False,
        ),
    ]
