# Generated by Django 5.0.1 on 2024-02-07 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jd', '0002_jd_trust'),
        ('speciality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jd',
            name='oncologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='speciality.oncologist'),
        ),
        migrations.AddField(
            model_name='jd',
            name='radiologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='speciality.radiologist'),
        ),
    ]
