# Generated by Django 5.0.1 on 2024-02-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jd', '0003_jd_oncologist_jd_radiologist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jd',
            name='oncologist',
        ),
        migrations.RemoveField(
            model_name='jd',
            name='radiologist',
        ),
    ]
