# Generated by Django 5.0.3 on 2024-03-29 17:35

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import viewflow.workflow.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('specialities', '0002_alter_consultanttype_name'),
        ('trusts', '0001_initial'),
        ('viewflow', '0012_alter_process_data_alter_task_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JDStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('RCR_APPROVED', 'RCR APPROVED'), ('RSA_APPROVED', 'RSA Review'), ('NEEDS_AMENDMENTS', 'Needs Amendments'), ('APPROVED', 'Approved')], default='SUBMITTED', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalJD',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('file', models.TextField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('consultant_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='specialities.consultanttype')),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trust', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='trusts.trust')),
            ],
            options={
                'verbose_name': 'historical jd',
                'verbose_name_plural': 'historical jds',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='JD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='JDs/')),
                ('consultant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialities.consultanttype')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('primary_specialities', models.ManyToManyField(related_name='primary_specialities', to='specialities.speciality')),
                ('sub_specialities', models.ManyToManyField(blank=True, related_name='sub_specialities', to='specialities.speciality')),
                ('trust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trusts.trust')),
            ],
        ),
        migrations.CreateModel(
            name='JDProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.process')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('jd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jds.jd')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jds.jdstatus')),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
        migrations.CreateModel(
            name='HistoricalJDProcess',
            fields=[
                ('process_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='viewflow.process')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('flow_class', viewflow.workflow.fields.FlowReferenceField(max_length=250, verbose_name='Flow')),
                ('status', models.CharField(choices=[('CANCELED', 'Canceled'), ('DONE', 'Done'), ('NEW', 'New')], default='NEW', max_length=50, verbose_name='Status')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='Finished')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('artifact_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('artifact_content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent_task', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='viewflow.task')),
                ('reviewer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('jd', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jds.jd')),
                ('review_status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jds.jdstatus')),
            ],
            options={
                'verbose_name': 'historical jd process',
                'verbose_name_plural': 'historical jd processs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
