# Generated by Django 5.0.4 on 2024-04-16 02:47

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialities', '0003_alter_consultanttype_name'),
        ('trusts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('consultant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_questions', to='specialities.consultanttype')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jds.question')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalJD',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('file', models.TextField(max_length=100)),
                ('requirements_met', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('consultant_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='specialities.consultanttype')),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trust', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='trusts.trust')),
            ],
            options={
                'verbose_name': 'historical jd',
                'verbose_name_plural': 'historical jds',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='JD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='JDs/')),
                ('requirements_met', models.BooleanField(default=False)),
                ('consultant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialities.consultanttype')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('primary_specialities', models.ManyToManyField(related_name='primary_specialities', to='specialities.speciality')),
                ('sub_specialities', models.ManyToManyField(blank=True, related_name='sub_specialities', to='specialities.speciality')),
                ('trust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trusts.trust')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('page_numbers', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('checklist_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_answers', to='jds.checklistquestion')),
                ('jd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_answers', to='jds.jd')),
            ],
        ),
        migrations.CreateModel(
            name='JDProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField(default=False)),
                ('rcr_approved', models.BooleanField(default=False)),
                ('rsa_approved', models.BooleanField(default=False)),
                ('ammended', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('jd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jds.jd')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
