# Generated by Django 5.0.2 on 2024-03-17 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='JDs/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('consultant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialities.consultanttype')),
            ],
        ),
    ]
