# Generated by Django 5.0.4 on 2024-04-16 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljd',
            name='reviewer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaljd',
            name='state',
            field=models.CharField(default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='jd',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_jds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jd',
            name='state',
            field=models.CharField(default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='jd',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_jds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='JDProcess',
        ),
    ]
