# Generated by Django 5.0.2 on 2024-03-17 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jds', '0001_initial'),
        ('specialities', '0001_initial'),
        ('trusts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jd',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jd',
            name='primary_specialities',
            field=models.ManyToManyField(related_name='primary_specialities', to='specialities.speciality'),
        ),
        migrations.AddField(
            model_name='jd',
            name='sub_specialities',
            field=models.ManyToManyField(related_name='sub_specialities', to='specialities.speciality'),
        ),
        migrations.AddField(
            model_name='jd',
            name='trust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trusts.trust'),
        ),
    ]
