# Generated by Django 5.0.3 on 2024-03-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jdstatus',
            name='status',
            field=models.CharField(choices=[('UNSUBMITTED', 'Unsubmitted'), ('SUBMITTED', 'Submitted'), ('RCR_APPROVED', 'RCR APPROVED'), ('RSA_APPROVED', 'RSA Review'), ('NEEDS_AMENDMENTS', 'Needs Amendments'), ('APPROVED', 'Approved')], default='SUBMITTED', max_length=20),
        ),
    ]
