# Generated by Django 5.0.3 on 2024-03-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jds', '0002_alter_jdstatus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaljdprocess',
            name='review_status',
        ),
        migrations.RemoveField(
            model_name='jdprocess',
            name='review_status',
        ),
        migrations.AddField(
            model_name='historicaljdprocess',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaljdprocess',
            name='rcr_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaljdprocess',
            name='rsa_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jdprocess',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jdprocess',
            name='rcr_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jdprocess',
            name='rsa_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='JDStatus',
        ),
    ]
