# Generated by Django 5.0.4 on 2024-04-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jds', '0002_historicaljd_reviewer_historicaljd_state_jd_reviewer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaljd',
            name='state',
        ),
        migrations.RemoveField(
            model_name='jd',
            name='state',
        ),
    ]
