# Generated by Django 5.0.2 on 2024-03-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jds', '0002_initial'),
        ('specialities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jd',
            name='sub_specialities',
            field=models.ManyToManyField(blank=True, related_name='sub_specialities', to='specialities.speciality'),
        ),
    ]
