# Generated by Django 5.0.3 on 2024-03-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jds', '0003_remove_historicaljdprocess_review_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljdprocess',
            name='ammended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jdprocess',
            name='ammended',
            field=models.BooleanField(default=False),
        ),
    ]
