# Generated by Django 5.0.4 on 2024-04-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jds', '0003_remove_historicaljd_state_remove_jd_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljd',
            name='state',
            field=models.CharField(default='draft', max_length=50),
        ),
        migrations.AddField(
            model_name='jd',
            name='state',
            field=models.CharField(default='draft', max_length=50),
        ),
    ]
