# Generated by Django 5.0.3 on 2024-03-30 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jds', '0004_historicaljdprocess_ammended_jdprocess_ammended'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalJDProcess',
        ),
    ]
