# Generated by Django 5.0.4 on 2024-04-16 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jds', '0004_historicaljd_state_jd_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaljd',
            old_name='state',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='jd',
            old_name='state',
            new_name='status',
        ),
    ]
