# Generated by Django 5.0.4 on 2024-04-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jds', '0005_rename_state_historicaljd_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljd',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jd',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
