# Generated by Django 5.0.4 on 2024-04-12 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jds', '0006_remove_jdprocess_submission_date_jdchecklist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='page_numbers',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='jdchecklist',
            name='jd',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jd_checklist', to='jds.jd'),
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='jds.jdchecklist')),
            ],
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='jds.checklist'),
        ),
    ]
