# Generated by Django 5.0.4 on 2024-04-16 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jds', '0006_alter_historicaljd_status_alter_jd_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaljd',
            name='status',
        ),
        migrations.RemoveField(
            model_name='jd',
            name='status',
        ),
    ]
