# Generated by Django 5.0.4 on 2024-04-12 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jds', '0007_alter_checklistitem_page_numbers_and_more'),
        ('specialities', '0003_alter_consultanttype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='consultant_type',
        ),
        migrations.AddField(
            model_name='checklist',
            name='consultant_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='specialities.consultanttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaljd',
            name='checklist',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jds.checklist'),
        ),
        migrations.AddField(
            model_name='jd',
            name='checklist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jd', to='jds.checklist'),
        ),
        migrations.DeleteModel(
            name='JDChecklist',
        ),
    ]
