# Generated by Django 5.0.4 on 2024-04-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jds', '0007_remove_historicaljd_status_remove_jd_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljd',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='jd',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
