# Generated by Django 5.0.4 on 2024-04-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jds', '0008_historicaljd_status_jd_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljd',
            name='status_edit_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='jd',
            name='status_edit_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaljd',
            name='status',
            field=models.CharField(default='Init', max_length=50),
        ),
        migrations.AlterField(
            model_name='jd',
            name='status',
            field=models.CharField(default='Init', max_length=50),
        ),
    ]
