# Generated by Django 5.0.4 on 2024-04-16 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jds', '0009_historicaljd_status_edit_date_jd_status_edit_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaljd',
            old_name='status_edit_date',
            new_name='status_date',
        ),
        migrations.RenameField(
            model_name='jd',
            old_name='status_edit_date',
            new_name='status_date',
        ),
    ]
