# Generated by Django 5.0.4 on 2024-04-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jds', '0010_rename_status_edit_date_historicaljd_status_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljd',
            name='diagram',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jd',
            name='diagram',
            field=models.ImageField(blank=True, null=True, upload_to='JDs/'),
        ),
    ]
