# Generated by Django 5.0.4 on 2024-04-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jds', '0010_question_alter_checklistquestion_checklist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaljd',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='jd',
            name='checklist',
        ),
    ]
