# Generated by Django 5.0.4 on 2024-04-12 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jds', '0011_remove_historicaljd_checklist_remove_jd_checklist'),
        ('specialities', '0003_alter_consultanttype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistquestion',
            name='checklist',
        ),
        migrations.AddField(
            model_name='checklistquestion',
            name='consultant_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='specialities.consultanttype'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
    ]
