# Generated by Django 5.0.4 on 2024-04-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jds', '0012_remove_checklistquestion_checklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistquestion',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
