# Generated by Django 5.0.4 on 2024-04-13 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jds', '0013_checklistquestion_active'),
        ('specialities', '0003_alter_consultanttype_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='checklistanswer',
            name='checklist_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_answers', to='jds.checklistquestion'),
        ),
        migrations.AlterField(
            model_name='checklistanswer',
            name='jd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_answers', to='jds.jd'),
        ),
        migrations.AlterField(
            model_name='checklistquestion',
            name='consultant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_questions', to='specialities.consultanttype'),
        ),
    ]
