# Generated by Django 5.0.3 on 2024-03-30 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('can_submit', 'Can submit a JD'), ('can_rcr_review', 'Can do an initial review'), ('can_rsa_review', 'Can do an RSA review')]},
        ),
    ]
