# Generated by Django 5.0.3 on 2024-03-30 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_alter_role_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
    ]
