# Generated by Django 5.0.1 on 2024-02-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jd', '0004_remove_jd_oncologist_remove_jd_radiologist'),
        ('speciality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Radiology', 'Radiology'), ('Oncology', 'Oncology')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Oncologist',
        ),
        migrations.DeleteModel(
            name='Radiologist',
        ),
    ]
