# Generated by Django 5.0.1 on 2024-02-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speciality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultanttype',
            name='name',
            field=models.CharField(choices=[('RADIOLOGIST', 'Radiologist'), ('ONCOLOGIST', 'Oncologist')], max_length=20, unique=True),
        ),
    ]
