# Generated by Django 5.0.1 on 2024-02-09 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speciality', '0002_alter_consultanttype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciality',
            name='consultant_type',
        ),
        migrations.AddField(
            model_name='speciality',
            name='consultant_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='speciality.consultanttype'),
            preserve_default=False,
        ),
    ]
