# Generated by Django 5.0.1 on 2024-02-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speciality', '0003_remove_speciality_consultant_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultanttype',
            name='name',
            field=models.CharField(choices=[('RADIOLOGY', 'Radiologist'), ('ONCOLOGY', 'Oncologist')], max_length=20, unique=True),
        ),
    ]
