# Generated by Django 5.0.2 on 2024-03-16 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('RADIOLOGY', 'Radiologist'), ('ONCOLOGY', 'Oncologist')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('consultant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialities.consultanttype')),
            ],
        ),
    ]
