# Generated by Django 5.0.3 on 2024-04-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialities', '0002_alter_consultanttype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultanttype',
            name='name',
            field=models.CharField(choices=[('RADIOLOGY', 'Radiology'), ('ONCOLOGY', 'Oncology')], max_length=20, unique=True, verbose_name='Role Name'),
        ),
    ]
