# Generated by Django 5.0.3 on 2024-03-30 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_alter_role_options'),
        ('specialities', '0002_alter_consultanttype_name'),
        ('trusts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={},
        ),
        migrations.AddField(
            model_name='userrole',
            name='consultant_type',
            field=models.ManyToManyField(blank=True, null=True, to='specialities.consultanttype'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='specialities',
            field=models.ManyToManyField(blank=True, null=True, to='specialities.speciality'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, through='users.UserRole', to='roles.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='trust',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trusts.trust'),
        ),
        migrations.AlterField(
            model_name='user',
            name='trust_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.role'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
