# Generated by Django 5.0.3 on 2024-03-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialities', '0002_alter_consultanttype_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RepresentativeInfo',
            new_name='Representative',
        ),
        migrations.RenameModel(
            old_name='ReviewerInfo',
            new_name='Reviewer',
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='specialities',
        ),
        migrations.AddField(
            model_name='reviewer',
            name='consultant_type',
            field=models.ManyToManyField(blank=True, to='specialities.consultanttype'),
        ),
    ]
