# Generated by Django 5.0.3 on 2024-03-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialities', '0002_alter_consultanttype_name'),
        ('users', '0002_alter_userrole_options_userrole_consultant_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='consultant_type',
            field=models.ManyToManyField(blank=True, to='specialities.consultanttype'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='specialities',
            field=models.ManyToManyField(blank=True, to='specialities.speciality'),
        ),
    ]
