# Generated by Django 5.0.3 on 2024-03-30 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialities', '0002_alter_consultanttype_name'),
        ('trusts', '0001_initial'),
        ('users', '0003_alter_userrole_consultant_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trust',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trust_approved',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='consultant_type',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='specialities',
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=4)),
                ('trust_approved', models.BooleanField(default=False)),
                ('consultant_type', models.ManyToManyField(blank=True, to='specialities.consultanttype')),
                ('specialities', models.ManyToManyField(blank=True, to='specialities.speciality')),
                ('trust', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trusts.trust')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
