# Generated by Django 5.0.1 on 2024-02-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_rcr_employee_user_is_representative_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='is_trust',
            field=models.BooleanField(default=False),
        ),
    ]
