# Generated by Django 5.0.2 on 2024-03-03 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCREmployeeInfo',
            fields=[
                ('user_role', models.OneToOneField(limit_choices_to={'role__name': 'RCR_EMPLOYEE'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.userrole', verbose_name='User Role')),
            ],
        ),
        migrations.CreateModel(
            name='TrustEmployeeInfo',
            fields=[
                ('user_role', models.OneToOneField(limit_choices_to={'role__name': 'TRUST_EMPLOYEE'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.userrole', verbose_name='User Role')),
            ],
        ),
    ]
