# Generated by Django 5.0.1 on 2024-02-03 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_user_type_user_is_trust'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('REVIEWER', 'Reviewer'), ('REPRESENTATIVE', 'Representative'), ('TRUST_EMPLOYEE', 'Trust Employee'), ('RCR_EMPLOYEE', 'RCR Employee'), ('', 'None')], default='', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_rcr_employee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_representative',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_reviewer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_trust',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
    ]
