# Generated by Django 5.0.3 on 2024-03-30 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trusts', '0001_initial'),
        ('users', '0005_remove_userprofile_title_user_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='trust_approved',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='trust',
        ),
        migrations.CreateModel(
            name='UserTrust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('trust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trusts.trust')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trust',
            field=models.ManyToManyField(blank=True, null=True, to='users.usertrust'),
        ),
    ]
