# Generated by Django 5.0.3 on 2024-03-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_roles_remove_userprofile_trust_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='trust',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trusts',
            field=models.ManyToManyField(blank=True, to='users.usertrust'),
        ),
    ]
