# Generated by Django 5.0.2 on 2024-03-03 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trusts', '0001_initial'),
        ('users', '0006_reviewerinfo_trust'),
    ]

    operations = [
        migrations.AddField(
            model_name='representativeinfo',
            name='trust',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trusts.trust', verbose_name='Trust'),
        ),
        migrations.AddField(
            model_name='trustemployeeinfo',
            name='trust',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trusts.trust', verbose_name='Trust'),
        ),
    ]
