# Generated by Django 5.0.2 on 2024-03-07 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('users', '0007_representativeinfo_trust_trustemployeeinfo_trust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='roles.role', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', through='users.UserRole', to='roles.role', verbose_name='User Roles'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
