# Generated by Django 5.0.3 on 2024-03-30 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialities', '0002_alter_consultanttype_name'),
        ('trusts', '0001_initial'),
        ('users', '0007_remove_userprofile_trust_userprofile_trusts'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSpecialities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='consultant_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='specialities',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='trusts',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='usertrust',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usertrust',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_trusts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='usertrust',
            constraint=models.UniqueConstraint(fields=('user', 'trust'), name='unique_user_trust'),
        ),
        migrations.AddField(
            model_name='userspecialities',
            name='consultant_type',
            field=models.ManyToManyField(blank=True, to='specialities.consultanttype'),
        ),
        migrations.AddField(
            model_name='userspecialities',
            name='specialities',
            field=models.ManyToManyField(blank=True, to='specialities.speciality'),
        ),
        migrations.AddField(
            model_name='userspecialities',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_specialities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
