# Generated by Django 5.0.3 on 2024-03-31 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialities', '0002_alter_consultanttype_name'),
        ('users', '0008_userspecialities_remove_userprofile_consultant_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userspecialities',
            name='consultant_type',
        ),
        migrations.AddField(
            model_name='userspecialities',
            name='consultant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='specialities.consultanttype'),
        ),
    ]
