# Generated by Django 5.0.2 on 2024-03-07 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trusts', '0001_initial'),
        ('users', '0008_alter_userrole_role_alter_user_roles_delete_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representativeinfo',
            name='trust',
        ),
        migrations.RemoveField(
            model_name='reviewerinfo',
            name='trust',
        ),
        migrations.RemoveField(
            model_name='trustemployeeinfo',
            name='trust',
        ),
        migrations.AddField(
            model_name='userrole',
            name='trust',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trusts.trust', verbose_name='Trust'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=4, verbose_name='Title'),
        ),
    ]
