# Generated by Django 5.0.2 on 2024-03-07 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trusts', '0001_initial'),
        ('users', '0009_remove_representativeinfo_trust_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='trust',
        ),
        migrations.AddField(
            model_name='user',
            name='trust',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trusts.trust', verbose_name='Trust'),
        ),
    ]
