# Generated by Django 5.0.1 on 2024-02-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_role_user_user_type_delete_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('REVIEWER', 'Reviewer'), ('REPRESENTATIVE', 'Representative'), ('TRUST_EMPLOYEE', 'Trust Employee'), ('RCR_EMPLOYEE', 'RCR Employee'), ('', 'None')], default='', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
