# Generated by Django 5.0.2 on 2024-03-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_userrole_trust_user_trust'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trust_approved',
            field=models.BooleanField(default=False, verbose_name='Trust Approved'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Role Approved'),
        ),
    ]
