# Generated by Django 5.0.1 on 2024-02-05 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='user_type',
            new_name='name',
        ),
    ]
