# Generated by Django 5.0.2 on 2024-03-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_trust_approved_alter_userrole_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='requested',
            field=models.BooleanField(default=False, verbose_name='Role Requested'),
        ),
    ]
