# Generated by Django 5.0.2 on 2024-03-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userrole_requested'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnauthenticatedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
    ]
