# Generated by Django 5.0.2 on 2024-03-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_unauthenticateduser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unauthenticateduser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
