# Generated by Django 5.0.1 on 2024-02-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20240205_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_be_reviewer', models.BooleanField(default=False)),
                ('can_be_representative', models.BooleanField(default=False)),
                ('can_be_rcr_employee', models.BooleanField(default=False)),
            ],
        ),
    ]
