# Generated by Django 5.0.2 on 2024-03-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_unauthenticateduser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unauthenticateduser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
