# Generated by Django 5.0.1 on 2024-02-07 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rolepermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermissions',
            name='role',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
    ]
