# Generated by Django 5.0.1 on 2024-02-08 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rolepermissions_remove_user_can_be_rcr_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='perms',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='users.rolepermissions'),
            preserve_default=False,
        ),
    ]
