# Generated by Django 5.0.1 on 2024-02-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_user_perms_user_can_be_rcr_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
